AllCops:
  TargetRubyVersion: 3.0
  Include:
    - 'lib/**/*.rb'
    - 'spec/**/*.rb'
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'gemfiles/**/*.gemfile'
    - 'gemfiles/vendor/**/*'
    - 'Rakefile'
    - 'Gemfile'
    - '*.gemspec'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/CyclomaticComplexity:
  Max: 8

Style/NumericLiterals:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false
