name: Rubocop

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
    - name: Lint Ruby code with RuboCop
      run: |
        bundle install --gemfile gemfiles/rails_7_0.gemfile --jobs 4 --retry 3
        bundle exec --gemfile gemfiles/rails_7_0.gemfile rubocop
